version: '3'

services:
  app:
    build: .
    entrypoint: dockerize -wait tcp://db:5432 -timeout 40s ./.docker/entrypoint.sh
    container_name: invoice-api-app
    ports:
      - 3002:3000
    volumes:
      - .:/home/node/app
    depends_on: 
      - db
    extra_hosts: 
        - 'host.docker.internal:172.17.0.1'

  db:
    build: .docker/postgres
    container_name: invoice-api-db
    restart: always
    tty: true
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=invoice

  pgadmin:
    image: dpage/pgadmin4
    container_name: invoice-api-pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - 9002:80